# Generated by Django 3.1.7 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SquirrelTracker',
            fields=[
                ('X', models.FloatField(help_text='Longitude')),
                ('Y', models.FloatField(help_text='Latitude')),
                ('Unique_Squirrel_ID', models.CharField(help_text='Unique Squirrel ID', max_length=50, primary_key=True, serialize=False, unique=True)),
                ('Shift', models.CharField(choices=[('PM', 'PM'), ('AM', 'AM')], help_text='shift', max_length=20)),
                ('Date', models.DateField(help_text='date')),
                ('Age', models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], help_text='Age', max_length=25, null=True)),
                ('Primary_Fur_Color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black')], help_text='Primary Fur Color', max_length=25, null=True)),
                ('Location', models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], help_text='Location', max_length=25, null=True)),
                ('Specific_Location', models.CharField(help_text='Specific Location', max_length=50, null=True)),
                ('Running', models.BooleanField(default=False, help_text='Running')),
                ('Chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('Climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('Eating', models.BooleanField(default=False, help_text='Eating')),
                ('Foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('Other_Activities', models.CharField(help_text='Other Activities', max_length=50, null=True)),
                ('Kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('Quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('Moans', models.BooleanField(default=False, help_text='Moans')),
                ('Tail_Flags', models.BooleanField(default=False, help_text='Tail Flags')),
                ('Tail_Twitches', models.BooleanField(default=False, help_text='Tail Twitches')),
                ('Approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('Indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('Runs_From', models.BooleanField(default=False, help_text='Runs From')),
            ],
        ),
    ]
